FROM maven:3.9.9-eclipse-temurin-17 AS build

WORKDIR /app

COPY pom.xml .
COPY core/pom.xml ./core/
COPY web/pom.xml ./web/

RUN mvn -B dependency:resolve dependency:resolve-plugins

COPY core/ ./core/
COPY web/ ./web/

RUN mvn -B package -Pweb -DskipTests

RUN gzip -9 web/target/dist/dict.json

RUN cat > default.conf <<EOF
server {
    listen 8080;
    root /usr/share/nginx/html;
    gzip_static always;
}
EOF

FROM nginxinc/nginx-unprivileged:1.27-alpine

COPY --from=build /app/default.conf /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html
COPY --from=build /app/web/target/dist/ ./

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
